#!/bin/bash
#
#
###############################################################################
# Copyright IBM Corp. and others 2025
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which accompanies this
# distribution and is available at https://www.eclipse.org/legal/epl-2.0/
# or the Apache License, Version 2.0 which accompanies this distribution and
# is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# This Source Code may also be made available under the following
# Secondary Licenses when the conditions for such availability set
# forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
# General Public License, version 2 with the GNU Classpath
# Exception [1] and GNU General Public License, version 2 with the
# OpenJDK Assembly Exception [2].
#
# [1] https://www.gnu.org/software/classpath/license.html
# [2] https://openjdk.org/legal/assembly-exception.html
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0 OR GPL-2.0-only WITH OpenJDK-assembly-exception-1.0
###############################################################################

# Some sections generated by Claude 3.7 Sonnet (version 20250219)

set -e

# Check if we're running with the -i option
if [[ "$*" == *"-i"* ]]; then
  # Get the UID and GID of the mounted files
  # We'll use the first file argument as reference
  FILE_ARG=""
  for arg in "$@"; do
    if [[ -f "$arg" ]]; then
      FILE_ARG="$arg"
      break
    fi
  done
  
  if [[ -n "$FILE_ARG" ]]; then
    OWNER_UID=$(stat -c "%u" "$FILE_ARG")
    OWNER_GID=$(stat -c "%g" "$FILE_ARG")
    
    # If the file is not owned by the current user, we need to run as the file owner
    if [[ "$OWNER_UID" != "$(id -u)" ]]; then
      echo "Running clang-format as UID:GID $OWNER_UID:$OWNER_GID to preserve file ownership"
      exec sudo -u "#$OWNER_UID" /opt/clang-tools/clang-format "$@"
    fi
  fi
fi

# If we're not using -i or couldn't determine the file owner, run normally
exec /opt/clang-tools/clang-format "$@"
